# Generated by Django 2.1 on 2018-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.CharField(max_length=128)),
                ('letters', models.CharField(blank=True, max_length=32)),
                ('results', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=16, null=True)),
                ('browser_string', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
